apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd
  namespace: kul
  labels: 
    app: httpd
  annotations: 
    githublink: https://github.com/kmayer10/epsilon.git
    maintainer: Kul
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        owner: kul
    spec: 
      containers: 
      - image: kulbhushanmayer/ericsson:bangalore-httpd-1.1
        name: httpd
        envFrom: 
        - secretRef: 
            name: mysqlpwd
        - configMapRef: 
            name: httpd-cm
        resources: 
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:           
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        kulNode: kul


  selector: 
    matchLabels: 
      owner: kul
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 1
