apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd
  namespace: kul
  labels: 
    app: httpd
  annotations: 
    githublink: https://github.com/kmayer10/epsilon.git
    maintainer: Kul
spec: 
  replicas: 3
  template: 
    metadata: 
      labels: 
        owner: kul
    spec: 
      containers: 
      - image: kulbhushanmayer/ericsson:bangalore-httpd-1.1
        name: httpd
      nodeSelector: 
        nodeName: kul
  selector: 
    matchLabels: 
      owner: kul
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 1
